kind: Service
apiVersion: v1
metadata:
  name: villa-agency-svc
  namespace: villa
  labels: 
    app: villa
    deploy: jenkins
spec:
  selector:
    app: villa
  type: NodePort
  ports:
  - name:  name-of-the-port
    port: 80
    targetPort: 80